// Tarshid-style Installation Completion Certificate (COC) PDF generator.
// Client-side, no server: pdf-lib + fontkit embed the Amiri TTF (Arabic + Latin,
// fetched from /public/fonts), and arabic-reshaper shapes Arabic into connected
// presentation forms (pdf-lib draws glyphs by codepoint and does no shaping/RTL,
// so we reshape + reverse for right-to-left display). Returns Uint8Array bytes.
import ArabicReshaper from 'arabic-reshaper'

const A4 = [595.28, 841.89]
const M = 40 // page margin
const GREEN = [0.0, 0.45, 0.30]
const DARK = [0.06, 0.09, 0.16]
const GREY = [0.4, 0.45, 0.5]
const LINE = [0.85, 0.88, 0.91]

const reshape = (t) => {
  try { const fn = ArabicReshaper.reshape || ArabicReshaper.convertArabic; return [...fn(String(t))].reverse().join('') }
  catch { return String(t) }
}

// Browser entry: fetch the embedded Amiri TTFs from /public/fonts, then render.
export async function generateCocPdf(data) {
  const base = import.meta.env.BASE_URL || '/'
  const [regBuf, boldBuf] = await Promise.all([
    fetch(base + 'fonts/Amiri-Regular.ttf').then((r) => r.arrayBuffer()),
    fetch(base + 'fonts/Amiri-Bold.ttf').then((r) => r.arrayBuffer()),
  ])
  return renderCocPdf(data, regBuf, boldBuf)
}

// Pure renderer (font bytes injected) — unit-testable outside the browser.
export async function renderCocPdf(data, regBuf, boldBuf) {
  const { PDFDocument, rgb } = await import('pdf-lib')
  const fontkit = (await import('@pdf-lib/fontkit')).default
  const pdf = await PDFDocument.create()
  pdf.registerFontkit(fontkit)
  const font = await pdf.embedFont(regBuf, { subset: true })
  const bold = await pdf.embedFont(boldBuf, { subset: true })
  const col = (c) => rgb(c[0], c[1], c[2])

  let page, y
  const newPage = () => { page = pdf.addPage(A4); y = A4[1] - M }
  const W = A4[0] - 2 * M

  const text = (s, x, yy, { size = 9, f = font, color = DARK, align = 'left', maxW } = {}) => {
    let str = String(s ?? '')
    const w = f.widthOfTextAtSize(str, size)
    let xx = x
    if (align === 'right') xx = x - w
    if (align === 'center') xx = x - w / 2
    if (maxW && w > maxW) { // crude truncation
      while (str.length > 1 && f.widthOfTextAtSize(str + '…', size) > maxW) str = str.slice(0, -1)
      str += '…'
    }
    page.drawText(str, { x: xx, y: yy, size, font: f, color: col(color) })
    return w
  }
  const ar = (s, x, yy, opts = {}) => text(reshape(s), x, yy, { ...opts, f: opts.f || font })
  const hline = (yy, x1 = M, x2 = A4[0] - M, c = LINE) => page.drawLine({ start: { x: x1, y: yy }, end: { x: x2, y: yy }, thickness: 0.7, color: col(c) })
  const box = (x, yy, w, h, c = LINE) => page.drawRectangle({ x, y: yy, width: w, height: h, borderColor: col(c), borderWidth: 0.7 })

  // bilingual section heading: green bar with Arabic (right) + English (left)
  const heading = (enLabel, arLabel) => {
    page.drawRectangle({ x: M, y: y - 16, width: W, height: 18, color: col(GREEN) })
    text(enLabel, M + 6, y - 12, { size: 9.5, f: bold, color: [1, 1, 1] })
    ar(arLabel, A4[0] - M - 6, y - 12, { size: 10, f: bold, color: [1, 1, 1], align: 'right' })
    y -= 26
  }
  // key/value row, bilingual key
  const kv = (en, arK, value) => {
    text(en, M, y, { size: 8.5, f: bold })
    ar(arK, M + 150, y, { size: 9, align: 'right' })
    text(value == null || value === '' ? '—' : String(value), M + 160, y, { size: 8.5, maxW: W - 165 })
    y -= 14
  }
  // generic table
  const table = (headers, widths, rows, { headColor = GREEN, rowH = 15 } = {}) => {
    const xs = []; let cx = M
    widths.forEach((w) => { xs.push(cx); cx += w * W })
    page.drawRectangle({ x: M, y: y - rowH + 3, width: W, height: rowH, color: col(headColor) })
    headers.forEach((h, i) => text(h, xs[i] + 3, y - rowH + 7, { size: 7.5, f: bold, color: [1, 1, 1], maxW: widths[i] * W - 6 }))
    y -= rowH
    rows.forEach((r, ri) => {
      if (y < M + 40) { drawFooter(); newPage(); y -= 4 }
      if (ri % 2 === 1) page.drawRectangle({ x: M, y: y - rowH + 3, width: W, height: rowH, color: rgb(0.97, 0.98, 0.99) })
      r.forEach((cell, i) => text(cell, xs[i] + 3, y - rowH + 7, { size: 7.5, maxW: widths[i] * W - 6 }))
      y -= rowH
    })
    hline(y + 2)
    y -= 6
  }
  let pageNo = 0
  const drawFooter = () => {
    pageNo += 1
    text(`${data.cocNo || 'COC'} · ${data.projectName || ''}`, M, 24, { size: 7, color: GREY })
    text(`Page ${pageNo}`, A4[0] - M, 24, { size: 7, color: GREY, align: 'right' })
    text('Generated by IES Programme Control Platform', A4[0] / 2, 24, { size: 7, color: GREY, align: 'center' })
  }

  // ── PAGE 1 — header, project info, description, installed items ─────────────
  newPage()
  box(M, y - 34, 70, 34); text('TARSHID', M + 8, y - 20, { size: 11, f: bold, color: GREEN }) // logo placeholder
  text('National Energy Services Company', M + 80, y - 12, { size: 10, f: bold, color: GREEN })
  ar('شركة الخدمات الوطنية للطاقة', A4[0] - M, y - 12, { size: 11, f: bold, color: GREEN, align: 'right' })
  ar('محضر إكتمال أعمال التركيب', A4[0] - M, y - 28, { size: 12, f: bold, align: 'right' })
  text('Installation Completion Certificate', M + 80, y - 28, { size: 10, f: bold })
  y -= 46
  text(`COC No: ${data.cocNo || '—'}`, M, y, { size: 9, f: bold, color: GREEN })
  text(`Revision ${data.revision || 'A'}`, A4[0] - M, y, { size: 9, f: bold, align: 'right' })
  y -= 10

  heading('Project Information', 'معلومات المشروع')
  kv('Project Name', 'اسم المشروع', data.projectName)
  kv('RFP / Contract No', 'رقم العقد', data.rfpNo || data.projectCode)
  kv('Contract / Start Date', 'تاريخ البدء', data.startDate)
  kv('End Date', 'تاريخ الانتهاء', data.endDate)
  kv('Executing Company', 'الشركة المنفذة', data.executingCompany)
  kv('Sub-Contractor', 'مقاول الباطن', data.subContractor)
  kv('Facility / Owner', 'المنشأة / المالك', data.facility)
  kv('Building Type', 'نوع المبنى', data.buildingType)
  kv('Region / City', 'المنطقة / المدينة', [data.region, data.city].filter(Boolean).join(' / '))
  kv('GPS Coordinates', 'الإحداثيات', data.gps)
  kv('Building IDs', 'أرقام المباني', data.buildingIds)
  kv('ESMs', 'إجراءات توفير الطاقة', data.esmLabels)

  heading('Description of Work', 'وصف الأعمال')
  text(data.description || '—', M, y, { size: 8.5, maxW: W }); y -= 16

  heading('Installed Items', 'المعدات المركبة')
  table(['#', 'Description', 'Model', 'Capacity', 'Efficiency', 'Qty'],
    [0.05, 0.34, 0.18, 0.16, 0.16, 0.11],
    data.installed.map((r, i) => [String(i + 1), r.item_description || '', r.model_code || '',
      r.capacity_value != null ? `${r.capacity_value} ${r.capacity_unit || ''}` : '',
      r.efficiency_value != null ? `${r.efficiency_value} ${r.efficiency_unit || ''}` : '', String(r.total_quantity ?? '')]))
  drawFooter()

  // ── PAGE 2 — removed items ─────────────────────────────────────────────────
  newPage()
  heading('Removed Items', 'المعدات المزالة')
  table(['#', 'Description', 'Capacity', 'Efficiency', 'Qty', 'Returned'],
    [0.05, 0.40, 0.16, 0.16, 0.10, 0.13],
    data.removed.map((r, i) => [String(i + 1), r.item_description || '',
      r.capacity_value != null ? `${r.capacity_value} ${r.capacity_unit || ''}` : '',
      r.efficiency_value != null ? `${r.efficiency_value} ${r.efficiency_unit || ''}` : '',
      String(r.total_quantity ?? ''), r.returned_to_facility ? 'Yes' : 'No']))
  drawFooter()

  // ── PAGE 3 — operating hours, electricity, attachments, signatures ─────────
  newPage()
  heading('Operating Hours & Electricity', 'ساعات التشغيل والكهرباء')
  kv('Daily Operating Hours', 'ساعات التشغيل اليومية', data.operatingHours || '—')
  kv('Electricity Company', 'شركة الكهرباء', data.electricityCompany || 'Saudi Electricity Company')
  kv('Account / Meter No', 'رقم الحساب / العداد', data.meterNo || '—')

  heading('Attachments', 'المرفقات')
  const attach = [['Specifications', 'المواصفات'], ['Detailed drawings', 'المخططات'], ['Photos', 'الصور'], ['Samples', 'العينات'], ['Inspection report', 'تقرير الفحص'], ['Test report', 'تقرير الاختبار'], ['Quantity reference', 'مرجع الكميات'], ['Other', 'أخرى']]
  let ax = M, ay = y
  attach.forEach((a, i) => {
    if (i > 0 && i % 2 === 0) { ay -= 18; ax = M }
    box(ax, ay - 10, 11, 11)
    text(a[0], ax + 16, ay - 8, { size: 8 })
    ar(a[1], ax + W / 2 - 10, ay - 8, { size: 8.5, align: 'right' })
    ax += W / 2
  })
  y = ay - 28

  heading('Approval', 'الاعتماد')
  const sigW = (W - 20) / 3
  const sigs = [['Executing Company', 'الشركة المنفذة'], ['Tarshid', 'ترشيد'], ['Government Representative', 'ممثل الجهة الحكومية']]
  sigs.forEach((s, i) => {
    const sx = M + i * (sigW + 10)
    box(sx, y - 96, sigW, 96)
    text(s[0], sx + 6, y - 12, { size: 8.5, f: bold })
    ar(s[1], sx + sigW - 6, y - 12, { size: 9, f: bold, align: 'right' })
    text('Name:', sx + 6, y - 36, { size: 8, color: GREY }); hline(y - 38, sx + 36, sx + sigW - 6)
    text('Role:', sx + 6, y - 54, { size: 8, color: GREY }); hline(y - 56, sx + 36, sx + sigW - 6)
    text('Signature:', sx + 6, y - 74, { size: 8, color: GREY }); hline(y - 76, sx + 56, sx + sigW - 6)
    text('Date:', sx + 6, y - 90, { size: 8, color: GREY }); hline(y - 92, sx + 36, sx + sigW - 6)
  })
  y -= 110
  drawFooter()

  return await pdf.save()
}
