import { useState } from 'react'
import { useAuth } from '../rbac'
import { useLiveQuery } from '../lib/db'
import { Modal, Field, inputStyle, Btn } from './ui'
import { compressImage } from '../lib/image'
import { toast } from '../lib/toast'
import { createInspectionDoc } from './CocWizard'

// Prefilled MIR / WIR generator. Shows the Tarshid template fields ready to go
// (project, generated-by, date), lets the user attach photos, then on Submit
// persists a project_documents row (visible in Doc Tracker + Project Documents)
// and downloads the generated PDF with the photos embedded.
export default function InspectionFormModal({ kind, project, esm = null, building = null, installed = [], material = '', onClose, onDone }) {
  const { user, profile } = useAuth()
  const today = new Date().toISOString().slice(0, 10)
  const [desc, setDesc] = useState(material || '')
  const [poRef, setPoRef] = useState('')
  const [projectRef, setProjectRef] = useState(project?.project_reference_no || '')
  const [beneficiary, setBeneficiary] = useState(project?.beneficiary_entity || project?.client || '')
  const [contractor, setContractor] = useState(project?.contractor_name || '')
  const [photos, setPhotos] = useState([]) // File[]
  const [busy, setBusy] = useState(false)
  const [esmId, setEsmId] = useState(esm?.id || '')
  const title = kind === 'mir' ? 'Generate MIR' : 'Generate WIR'
  const generatedBy = profile?.full_name || user?.email || ''

  // ESM options so the submittal always lands in the right Doc Tracker cell
  const { rows: pEsms } = useLiveQuery('project_esms',
    (q) => q.select('esm:esms(id,code,name),custom_name,ordinal').eq('project_id', project?.id).order('ordinal'), [project?.id])
  const esmOpts = pEsms.filter((pe) => pe.esm).map((pe) => ({ id: pe.esm.id, code: pe.esm.code, name: pe.custom_name || pe.esm.name }))
  const chosenEsm = esmOpts.find((e) => e.id === esmId) || esm || null

  const addPhotos = (e) => {
    const files = Array.from(e.target.files || [])
    if (files.length) setPhotos((p) => [...p, ...files])
    e.target.value = ''
  }
  const removePhoto = (i) => setPhotos((p) => p.filter((_, idx) => idx !== i))

  const submit = async () => {
    if (!project) { toast('No project context', 'err'); return }
    setBusy(true)
    // shrink images so the embedded photos keep the PDF light
    let photoFiles = photos
    try { photoFiles = await Promise.all(photos.map((f) => (f.type.startsWith('image/') ? compressImage(f, { maxBytes: 400000, maxDim: 1400 }) : f))) } catch { photoFiles = photos }
    const res = await createInspectionDoc({
      kind, project, esm: chosenEsm, building, installed, userId: user.id,
      generatedBy, material: desc.trim() || undefined, poRef: poRef.trim() || undefined, photoFiles,
      extra: { projectRef: projectRef.trim(), beneficiary: beneficiary.trim(), contractor: contractor.trim() },
    })
    setBusy(false)
    if (res?.error) { toast(`${kind.toUpperCase()} generation failed — ${res.error.message || ''}`, 'err'); return }
    // download the generated PDF for the engineer to sign
    if (res.path) {
      const { signedUrlFor } = await import('../lib/db')
      const url = await signedUrlFor('project-docs', res.path)
      if (url) window.open(url, '_blank', 'noopener')
    }
    toast(`${res.docNo} generated — added to Doc Tracker`)
    onDone?.()
    onClose?.()
  }

  const readOnly = { ...inputStyle, background: '#F8FAFC', color: 'var(--text-3)' }
  return (
    <Modal open width={560} title={title} onClose={onClose}
      footer={<><Btn onClick={onClose}>Cancel</Btn><Btn variant="primary" onClick={submit} disabled={busy}>{busy ? 'Generating…' : 'Generate & download PDF'}</Btn></>}>
      <div style={{ fontSize: 12.5, color: 'var(--text-3)', marginBottom: 12 }}>
        The {kind.toUpperCase()} PDF is filled from the fields below and saved to the Doc Tracker. Add site photos to embed them in the form — then just add a wet signature and send to the client.
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
        <Field label="Project"><input lang="en" style={readOnly} value={`${project?.name || ''} (${project?.code || ''})`} readOnly /></Field>
        <Field label="Generated by"><input lang="en" style={readOnly} value={generatedBy} readOnly /></Field>
        <Field label="Date"><input lang="en" style={readOnly} value={today} readOnly /></Field>
        <Field label="ESM (which Doc Tracker row this lands in)">
          <select style={inputStyle} value={esmId} onChange={(e) => setEsmId(e.target.value)}>
            <option value="">— Not ESM-specific —</option>
            {esmOpts.map((e) => <option key={e.id} value={e.id}>{e.code} · {e.name}</option>)}
          </select>
        </Field>
      </div>
      <Field label="Material / equipment description"><textarea style={{ ...inputStyle, minHeight: 54, resize: 'vertical' }} value={desc} onChange={(e) => setDesc(e.target.value)} placeholder="What is being inspected" /></Field>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
        <Field label="Project Reference No"><input lang="en" style={inputStyle} value={projectRef} onChange={(e) => setProjectRef(e.target.value)} placeholder="e.g. 2022005" /></Field>
        <Field label="Contractor"><input lang="en" style={inputStyle} value={contractor} onChange={(e) => setContractor(e.target.value)} placeholder="Contractor name" /></Field>
        <Field label="Beneficiary Entity"><input lang="en" style={inputStyle} value={beneficiary} onChange={(e) => setBeneficiary(e.target.value)} placeholder="Beneficiary entity" /></Field>
        <Field label="PO / Contract reference (optional)"><input lang="en" style={inputStyle} value={poRef} onChange={(e) => setPoRef(e.target.value)} placeholder="e.g. PO-2026-00417" /></Field>
      </div>
      <Field label={`Photos (${photos.length}) — embedded in the PDF`}>
        <label className="ies-hover" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '8px 12px', border: '1px dashed var(--line)', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer' }}>
          + Add photos<input type="file" accept="image/*" multiple onChange={addPhotos} style={{ display: 'none' }} />
        </label>
      </Field>
      {photos.length > 0 && (
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 8 }}>
          {photos.map((f, i) => (
            <div key={i} style={{ position: 'relative', width: 72, height: 72, borderRadius: 8, overflow: 'hidden', border: '1px solid var(--line)' }}>
              <img src={URL.createObjectURL(f)} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
              <button onClick={() => removePhoto(i)} title="Remove" style={{ position: 'absolute', top: 2, right: 2, width: 18, height: 18, borderRadius: '50%', background: 'rgba(0,0,0,.6)', color: '#fff', fontSize: 12, lineHeight: '16px' }}>×</button>
            </div>
          ))}
        </div>
      )}
    </Modal>
  )
}
