-- supabase/migrations/0024_business_seed.sql
-- IES Programme Control Platform v2 — Phase 3, migration 24
--
-- ===========================================================================
-- GUTTED — CONTENT REMOVED UNDER CONSTRAINTS #7 (confidentiality cleanup).
-- ===========================================================================
-- This migration was a demo seed: two fabricated programmes with their
-- buildings, rooms, ESM scope, install log, tasks, escalations, documents and
-- material movements. It carried a real ministry's name and a real-looking
-- facility naming scheme as illustrative filler, which is exactly the kind of
-- content that should never have been written into a public repository — the
-- data was invented, but the client identity in it was not.
--
-- THE ROWS THEMSELVES ARE ALREADY GONE FROM THE DATABASE. Migration
-- 0126 purged this demo data (see docs/Purge-0126-Proof.md), so removing the
-- statements here changes no live state; it removes a copy of the identifiers
-- that no longer corresponds to anything, and would otherwise be re-inserted
-- by any fresh rebuild from the migration series.
--
-- THE FILE IS KEPT AS A NUMBERED NO-OP so the migration ledger and the file
-- series stay aligned: 0024 has been applied on every existing environment,
-- and deleting the file would leave a hole between 0023 and 0025 that no
-- runner and no reader could account for. It executes nothing.
--
-- Nothing below this line. Any future seed data belongs in its own migration,
-- and per Constraints #7 must carry no client-identifying names.
